### ISSUE TITLE
Python 3.13 incompatibility: missing 'cgi' module

### ISSUE THREAD

**Issue by nicozanf** [valq7711/ombott#19]
Hi,

after being deprecated (see #10), the 'cgi' module has been totally removed from python 3.13.0 - where now ombott 2.2 cannot run. Maybe the 2.0rc2 proposed fix could be ported on 2.2?

BTW: this is reflected on py4web incompatibility with python 3.13, see [here](https://github.com/web2py/py4web/issues/928).

**Comment by valq7711** [comment]
Hi! try ombott 2.3

**Comment by nicozanf** [comment]
Hi!
Well, the simple "Hello World" example works fine, so I think we can close this issue.

Unfortunately, I've discovered the same problem with pyDAL so I cannot test it better with py4web. I've just opened an issue there https://github.com/web2py/pydal/issues/718
