### ISSUE TITLE
Non ascii characters are not sent to db

### ISSUE THREAD

**Issue by jparga** [valq7711/ombott#7]
Non ascii characters are stored in db through py4web form,

Changing recode_unicode=False in line 143 of request/helpers.py seems to solve the problem
https://github.com/valq7711/ombott/blob/f18f6e0e639f20efb63b137edbab8c8b3871d354/ombott/request/helpers.py#L143

**Comment by valq7711** [comment]
Ascii characters entered in the form become non-ascii?
Could you povide more details, please?

**Comment by jparga** [comment]
No, non ascii characters cause an error and the value is not stored in the db.
If the record is edited from an existing one then the value of the fields with no ascii characters is set to None.
If there is a IS_NOT_EMPTY() validator then the error 'Enter a value' rises.
This is the explanation of the error.
https://groups.google.com/g/py4web/c/s5W-8zgvmoA/m/Fn3mRYwrCQAJ

This is the patched solution: 
https://discord.com/channels/836984759535534120/836984759535534125/1006343351190171718

**Comment by valq7711** [comment]
OK, will fix
https://github.com/bottlepy/bottle/pull/1068

**Comment by valq7711** [comment]
fixed https://github.com/valq7711/ombott/commit/fcb2abe53e8572144d7b1fcaf06e5dbb73955ff2
