### ISSUE TITLE
duplicated cookies

### ISSUE THREAD

**Issue by mdipierro** [valq7711/ombott#9]
Have been having issues with duplicated cookies entries, for example: Cookie: _formkey=aaaa; _formkey=bbbb

The only solutions that fixed it for me was:

```
def delete_cookie(key):
    if response._cookie and key in response._cookie:
        del response._cookie[key]
```

and calling delete_cookie always before response.set_cookie(key, ....)

**Comment by valq7711** [comment]
Sorry for the late response, is it still an issue? I can't reproduce

**Comment by mdipierro** [comment]
Issue has not manifested any more
